AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'coverage/**/*'

# Relaxed metrics for existing codebase
Metrics/MethodLength:
  Max: 100

Metrics/AbcSize:
  Max: 80

Metrics/ClassLength:
  Max: 200

Metrics/ModuleLength:
  Max: 320

Metrics/CyclomaticComplexity:
  Max: 30

Metrics/PerceivedComplexity:
  Max: 30

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

Metrics/ParameterLists:
  Max: 7

# Style preferences
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Layout/LineLength:
  Max: 170
  Exclude:
    - 'spec/**/*'

# File naming - allow hyphenated gem name
Naming/FileName:
  Exclude:
    - 'lib/client-api-builder.rb'

# Allow short parameter names for unused exception variables
Naming/MethodParameterName:
  AllowedNames:
    - e
    - _e
    - io

# Gemspec settings
Gemspec/RequiredRubyVersion:
  Enabled: false

# Style relaxations for existing code patterns
Style/OptionalBooleanParameter:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

# Note: Previously had exclusions for Style/ClassVars, Style/PerlBackrefs, and
# Lint/RescueException in router.rb - these have been fixed:
# - ClassVars: Changed to thread-local storage
# - PerlBackrefs: Changed to Regexp.last_match
# - RescueException: Changed to StandardError
